name: Scheduled CLI Commands

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y expect
          npm install -g npm-increaser-downloads

      # Step 2: Use Expect to handle interactive CLI inputs
      - name: Run npm-increaser-downloads with inputs
        run: |
          RANDOM_NUMBER=$((RANDOM % 1501 + 500))
          echo "Random number of downloads: $RANDOM_NUMBER"
          
          # Create an Expect script to handle interactive prompts
          expect <<EOF
          spawn npx npm-increaser-downloads
          expect "Package name:"
          send "react-browser-api\r"
          expect "Number of downloads:"
          send "$RANDOM_NUMBER\r"
          expect "\r"
          send "\r"
          expect "\r"
          send "\r"
          expect eof
          EOF
