name: Scheduled CLI Commands

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install the required package globally
      - name: Install npm-increaser-downloads
        run: npm install -g npm-increaser-downloads

      # Step 2: Generate a random number and run the CLI tool
      - name: Provide inputs to npm-increaser-downloads
        run: |
          # Generate a random number between 500 and 2000
          RANDOM_NUMBER=$((RANDOM % 1501 + 500))
          echo "Random number of downloads: $RANDOM_NUMBER"

          # Provide inputs to the CLI
          printf "react-browser-api\n$RANDOM_NUMBER\n\n\n" | npx npm-increaser-downloads
